### ISSUE TITLE
engine_version causes cluster update in place on every apply

### ISSUE THREAD

**Issue by peterkools** [umotif-public/terraform-aws-elasticache-redis#16]
**What is the current behavior?**

I have a module configured as show below. Each time I run `terraform apply`, I get a notification that the engine_version will be updated from "6.0.5" to "6.x". This doesn't actually cause a change in the provisioned cluster, but appears to be a housekeeping issue as the engine_version cannot use "6.0.5" in the module.

```
module "elasticache-redis" {
  source                     = "umotif-public/elasticache-redis/aws"
  version                    = "~> 2.0"
  name_prefix                = "${var.app}-${var.env}-redis3"
  number_cache_clusters      = 3
  node_type                  = "cache.t3.small"
  multi_az_enabled           = true
  automatic_failover_enabled = true
  cluster_mode_enabled       = false
  engine_version             = "6.x"
  family                     = "redis6.x"
  port                       = 6379
  security_group_ids         = [aws_default_security_group.default.id]
  maintenance_window         = "sun:05:00-sun:06:00"
  snapshot_window            = "06:00-08:00"
  snapshot_retention_limit   = 7
  auto_minor_version_upgrade = true
  at_rest_encryption_enabled = true
  transit_encryption_enabled = false
  apply_immediately          = true
  subnet_ids                 = module.vpc.public_subnets
  vpc_id                     = module.vpc.vpc_id
  final_snapshot_identifier  = var.elasticache_final_snapshot_identifier

  availability_zones = [
    data.aws_availability_zones.available.names[0],
    data.aws_availability_zones.available.names[1],
    data.aws_availability_zones.available.names[2]
  ]

  # Currently unsupported for this module.
  # lifecycle {
  #   ignore_changes = [engine_version]
  # }
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a module specification with engine_version="6.x".
2. `terraform apply` to create the cache.
3. `terraform apply` a second time to observe the plan change.

**What is the expected behavior?**

Best would be that there would not be a change in the plan. As an alternative, supporting a lifecycle ignore_changes for engine_version would enable a work around.

**Software versions?**

Terraform 0.15.1
hashicorp/aws version 3.37.0
umotif-public/elasticache-redis/aws version 2.0.0

**Comment by marcincuber** [comment]
Yep, this is a terraform aws provider issue. I believe this has been fixed in the latest version which is 3.38.0. So just upgrade your provider and you should be sorted :)
