### ISSUE TITLE
Wrong parameter in usage documentation

### ISSUE THREAD

**Issue by ghost** [umotif-public/terraform-aws-elasticache-redis#27]
**What is the current behaviour?**
I used `number_cache_clusters` as suggested on the [Usage example in Readme](https://github.com/umotif-public/terraform-aws-elasticache-redis/blob/main/README.md?plain=1#L22) and caused
```

╷
│ Error: Unsupported argument
│
│   on redis.tf line 6, in module "elasticache-redis":
│    6:   number_cache_clusters = 1
│
│ An argument named "number_cache_clusters" is not expected here.
```
The right value is `num_cache_cluster`

**Comment by Ohid25** [comment]
Thank you for raising an inconsistency in the documentation. This is now resolved and included in the latest release - [3.1.1](https://github.com/umotif-public/terraform-aws-elasticache-redis/releases/tag/3.1.1)
