### ISSUE TITLE
Unable to create secondary replica for aws_elasticache_global_replication_group

### ISSUE THREAD

**Issue by vinfang** [umotif-public/terraform-aws-elasticache-redis#31]
**What is the current behavior?**
When using the module in a different region to create a secondary replica group with global_replication_group_id, end up with error

`│ Error: error creating ElastiCache Replication Group (prod-redis-replica): InvalidParameterCombination: Cannot use the given parameters when creating new replication group in an existing global replication group.
│ 	status code: 400, request id: 1e6bd0b5-8c46-4589-b573-3bbed3e98e47
│
│   with module.redis.aws_elasticache_replication_group.redis,
│   on .terraform/modules/redis/main.tf line 1, in resource "aws_elasticache_replication_group" "redis":
│    1: resource "aws_elasticache_replication_group" "redis" {
│` 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is the bare minimum we tried to use in our Terraform template for the secondary replica in a different region.

```
module "redis" {
  source = "umotif-public/elasticache-redis/aws"
  version = "~> 3.0"

  global_replication_group_id = data.terraform_remote_state.primary_redis.outputs.global_replication_group_id

  name_prefix        = "prod"
  node_type          = "cache.r6g.2xlarge"
  family                 = "redis6.x"

  subnet_ids = data.aws_subnets.private_subnets.ids
  vpc_id        = data.aws_vpc.vpc.id

  ingress_cidr_blocks     = var.ingress_cidr_ips
  allowed_security_groups = var.ingress_security_group_ids

 }
```

Our primary cluster looks like this

```
resource "aws_elasticache_global_replication_group" "global" {
  global_replication_group_id_suffix = "prod-primary"
  primary_replication_group_id       = module.redis.elasticache_replication_group_id
}


module "redis" {
  source = "umotif-public/elasticache-redis/aws"
  version = "~> 3.0"

  automatic_failover_enabled = false
  auto_minor_version_upgrade = false

  name_prefix        = "prod"
  num_cache_clusters = 1
  node_type          = "cache.r6g.2xlarge"
  family             =  "redis6.x"
  engine_version     = "6.x"
  port               = 6379

  at_rest_encryption_enabled = false
  transit_encryption_enabled = false
  apply_immediately = true

  subnet_ids = data.aws_subnets.private_subnets.ids
  vpc_id     = data.aws_vpc.vpc.id

  ingress_cidr_blocks     = var.ingress_cidr_ips
  allowed_security_groups = var.ingress_security_group_ids
}
```

**What is the expected behavior?**
The module used as the secondary replica should be able to create it without the InvalidParameterCombination. I really wish the provider would output which parameters are not good.

What we ended up doing to create our secondary replica cluster was creating the actual resources without the module like so. We ran into errors while trying to set some attributes, so we had to go with whatever defaults without touching as much as possible to get it created:

```
resource "aws_elasticache_replication_group" "secondary" {
  replication_group_id        = "prod-redis-replica"
  description                 = "secondary replication group"
  global_replication_group_id = data.terraform_remote_state.primary_redis.outputs.global_replication_group_id
  subnet_group_name           = aws_elasticache_subnet_group.redis.name
  security_group_ids          = [aws_security_group.redis.id]

  lifecycle {
    ignore_changes = [engine_version]
  }
}

resource "aws_elasticache_subnet_group" "redis" {
  name        = "prod-redis-sg-replica"
  subnet_ids  = data.aws_subnets.private_subnets.ids
}

resource "aws_security_group" "redis" {
  name_prefix = "prod-redis"
  vpc_id      = data.aws_vpc.vpc.id

  lifecycle {
    create_before_destroy = true
  }
}

# What security groups are allowed to talk to this?
resource "aws_security_group_rule" "ingress_sg_ids" {
  count = length(var.ingress_security_group_ids)
  type                     = "ingress"
  from_port                = 6379
  to_port                  = 6379
  protocol                 = "tcp"
  source_security_group_id = var.ingress_security_group_ids[count.index]
  security_group_id        = aws_security_group.redis.id
}

# What IPs are allowed to talk to this?
resource "aws_security_group_rule" "ingress_ips" {
  count = length(var.ingress_cidr_ips) > 0 ? 1 : 0
  type              = "ingress"
  from_port         = 6379
  to_port           = 6379
  protocol          = "tcp"
  cidr_blocks       = var.ingress_cidr_ips
  security_group_id = aws_security_group.redis.id
}
```

**Software versions?**
We're using Terraform 1.0.3 and AWS Provider 4.18.0. There is a GitHub thread discussing this issue, https://github.com/hashicorp/terraform-provider-aws/issues/24854, that may have been recently fixed, but even with updating to `4.18.0`, we still ran into the InvalidParameterCombination error, until we created one without the module.

**Comment by Ohid25** [comment]
I think this is solved with this #32. I think what was missing was data tiering.
