### ISSUE TITLE
Recreating the Redis cluster does not work

### ISSUE THREAD

**Issue by fbergero** [umotif-public/terraform-aws-elasticache-redis#37]
**What is the current behavior?**
Currently the module tries to create the replication group before destroying any previous existing one.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create a cluster
- Change any parameter that requires re-creating (Encryption enabled for example)
- Re apply
- The API to create the new version of the cluster will fail since there is already a replication group with than name.

**What is the expected behavior?**
The module should remove the existing cluster first and then create the replacement. 
This should be removed
https://github.com/umotif-public/terraform-aws-elasticache-redis/blob/main/main.tf#L82

**Software versions?**

**Comment by Ohid25** [comment]
Thank you for raising the issue! This should now be resolved with [3.5.0](https://github.com/umotif-public/terraform-aws-elasticache-redis/releases/tag/3.5.0). If there are any issues, please open another issue, and we will look into it as soon as possible.
