### ISSUE TITLE
Parameter group description

### ISSUE THREAD

**Issue by KamranBiglari** [umotif-public/terraform-aws-elasticache-redis#43]
Since the parameter group description is immutable. If I change the `description` value it's going to recreate the parameter group.
I believe you need two description variables, one for elasticache and one for parameter group.

**Comment by Ohid25** [comment]
Thank you for raising the issue! This should now be resolved with [3.5.0](https://github.com/umotif-public/terraform-aws-elasticache-redis/releases/tag/3.5.0). If there are any issues, please open another issue and we will look into it as soon as we can.
