### ISSUE TITLE
Sub-modules should not constrain maximum provider version

### ISSUE THREAD

**Issue by gavllew** [umotif-public/terraform-aws-elasticache-redis#45]
**What is the current behavior?**

The module constrains both the minimum and maximum provider versions:

https://github.com/umotif-public/terraform-aws-elasticache-redis/blob/b3862cd6ccdec8edc722600773953144d2ec3f6e/versions.tf#L4-L7

**What is the expected behavior?**

The [best practices for Terraform provider versions](https://developer.hashicorp.com/terraform/language/providers/requirements#best-practices-for-provider-versions) suggest that only root modules should specify the maximum supported provider versions; sub-modules should not:

> Do not use ~> (or other maximum-version constraints) for modules you intend to reuse across many configurations, even if you know the module isn't compatible with certain newer versions. Doing so can sometimes prevent errors, but more often it forces users of the module to update many modules simultaneously when performing routine upgrades. Specify a minimum version, document any known incompatibilities, and let the root module manage the maximum version.

**Software versions?**

3.3.0

**Comment by czenker** [comment]
Just to add the obvious: This currently prevents any stack that uses this module to update to AWS Provider version 5.

An alternative could be to release a version that is compatible with AWS Provider version 5.
